use `exams-automation`;

CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `ROLE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL UNIQUE,  
  `PASSWORD` VARCHAR(15) NOT NULL default 'abcd1234',
  PRIMARY KEY (`ID`)  
);

CREATE TABLE `SUBJECT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL UNIQUE,
  `DESCRIPTION` VARCHAR(100),
  PRIMARY KEY (`ID`)  
);


CREATE TABLE `USER_SUBJECT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `SUBJECT_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`USER_ID`, `SUBJECT_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`ID`),
  FOREIGN KEY (`SUBJECT_ID`) REFERENCES `SUBJECT`(`ID`)
);

CREATE TABLE `COMPLEXITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LEVEL` VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `QUESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SUBJECT_ID` INT NOT NULL,
  `QUESTION` VARCHAR(512) NOT NULL,
  `QUESTION_TYPE` VARCHAR(25) NOT NULL,
  `COMPLEXITY_ID` INT NOT NULL,
  `CREATED_BY` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`SUBJECT_ID`, `QUESTION`),
  UNIQUE KEY (`SUBJECT_ID`, `QUESTION`, `QUESTION_TYPE`, `COMPLEXITY_ID`),
  FOREIGN KEY (`SUBJECT_ID`) REFERENCES `SUBJECT`(`ID`),
  FOREIGN KEY (`COMPLEXITY_ID`) REFERENCES `COMPLEXITY`(`ID`),
  FOREIGN KEY (`CREATED_BY`) REFERENCES `USER`(`ID`)
);

CREATE TABLE `ANSWER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QUESTION_ID` INT NOT NULL,
  `ANSWER` VARCHAR(256) NOT NULL,
  `IS_CORRECT` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`QUESTION_ID` , `ANSWER`),
  FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTION`(`ID`)
);


CREATE TABLE `TEST_PAPER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SUBJECT_ID` INT NOT NULL,
  `CREATED_BY` INT NOT NULL,
  `TYPE` VARCHAR(50) NOT NULL,
  `DURATION_MINUTES` INT,
  `CREATED_DATE` TIMESTAMP,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`SUBJECT_ID`) REFERENCES `SUBJECT`(`ID`),
  FOREIGN KEY (`CREATED_BY`) REFERENCES `USER`(`ID`)
);


CREATE TABLE `TEST_PAPER_QUESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEST_PAPER_ID` INT NOT NULL,
  `QUESTION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`TEST_PAPER_ID`, `QUESTION_ID`),
  FOREIGN KEY (`TEST_PAPER_ID`) REFERENCES `TEST_PAPER`(`ID`),
  FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTION`(`ID`)
);


CREATE TABLE `STUDENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL UNIQUE,
  `MOBILE` VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (`ID`)
);


CREATE TABLE `STUDENT_TEST_PAPER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` INT NOT NULL,
  `TEST_PAPER_ID` INT NOT NULL,
  `STATUS` VARCHAR(20), -- e.g., "Completed", "Pending", "TimedOut"
  `START_TIME` TIMESTAMP,
  `SUBMIT_TIME` TIMESTAMP,
  `SCORE` INT,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`STUDENT_ID`,`TEST_PAPER_ID`),
  FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT`(`ID`),
  FOREIGN KEY (`TEST_PAPER_ID`) REFERENCES `TEST_PAPER`(`ID`)
);


-- Drop commands

drop table student_test_paper;
drop table student;
drop table test_paper_question;
drop table test_paper;
drop table answer;
drop table question;
drop table complexity;
drop table user_subject;
drop table subject;
drop table user;









